name: Bug report for Drakkar
description: File a detailed bug report so we can reproduce and fix the issue
title: "[Bug] "
labels: ["needs-confirmation"]

body:
  - type: markdown
    attributes:
      value: "# Issue Details"

  - type: textarea
    attributes:
      label: Issue Description
      description: |
        Provide a detailed description of the issue. Include relevant information, such as:
        - Screenshots, screen recordings, Hanabi assets, or other supporting media.
        - If this is a regression, link the previous discussion/issue/PR/commit.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe the behavior you **expected** Drakkar to have.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: Describe the behavior Drakkar **actually** shows and how it differs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Provide precise steps so we can reproduce the bug.
      placeholder: |
        1. Open Drakkar
        2. Select asset file
        3. …
    validations:
      required: true

  - type: textarea
    attributes:
      label: Drakkar Logs
      description: |
        Paste logs or stack traces captured while reproducing the issue.
        (Run Drakkar with `RUST_LOG=debug` to enable debug logs.)
      render: text

  - type: textarea
    attributes:
      label: Drakkar Version
      description: Paste the output of `drakkar-vfx --version`.
      placeholder: |
        Drakkar VFX 0.1.0-dev
        Build Information:
          Git SHA: 86b61559…
          Git Commit Date: 2025-07-07T21:00:58Z
          Rust Version: 1.89.0-nightly
          Target: aarch64-apple-darwin
          Build Date: 2025-07-07T21:28:02Z
      render: text
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version Information
      description: Tell us the OS name and version you’re using.
      placeholder: Ubuntu 24.04 (Noble Numbat)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: (Linux only) Display Server
      description: |
        If you run Linux, choose your display server.
        Unsure? Run `[ -z "$WAYLAND_DISPLAY" ] && echo X11 || echo Wayland`.
      options:
        - X11
        - Wayland
        - Other
    validations:
      required: false
