 [target.x86_64-pc-windows-msvc]
 linker = "rust-lld.exe"
 rustflags = [
     "-Ctarget-cpu=native",
     "-Zlocation-detail=none",
     "-Zshare-generics=y"
 ]
 [target.x86_64-apple-darwin]
 rustflags = [
     "-Ctarget-cpu=native",
     "-Zlocation-detail=none",
     "-Zshare-generics=y"
 ]
 [target.aarch64-apple-darwin]
 rustflags = [
     "-Ctarget-cpu=native",
     "-Zlocation-detail=none",
     "-Zshare-generics=y"
 ]
 [target.x86_64-linux-gnu]
 rustflags = [
     "-Ctarget-cpu=native",
     "-Zlocation-detail=none",
     "-Zshare-generics=y"
 ]
 [target.x86_64-linux-musl]
 rustflags = [
     "-Ctarget-cpu=native",
     "-Zlocation-detail=none",
     "-Zshare-generics=y"
 ]
